import { createMockLevel } from "./helpers";
import type { Level } from "@/types/game";

export const vocabularyLevels = [
  createMockLevel({
    id: "1",
    bookId: "nce-1",
    unitId: "nce-1-u1",
    title: "Animal Starters",
    difficulty: "easy",
    rewardCoins: 20,
    hintCost: 25,
    perfectBonusCoins: 5,
    mainWord: "CAT",
    miniWords: ["CAR", "ANT", "TOP"]
  }),
  createMockLevel({
    id: "2",
    bookId: "nce-1",
    unitId: "nce-1-u1",
    title: "Bag Basics",
    difficulty: "easy",
    rewardCoins: 20,
    hintCost: 25,
    perfectBonusCoins: 5,
    mainWord: "BAG",
    miniWords: ["BAT", "ARM", "GEM"]
  }),
  createMockLevel({
    id: "3",
    bookId: "nce-1",
    unitId: "nce-1-u1",
    title: "Sunny Words",
    difficulty: "easy",
    rewardCoins: 25,
    hintCost: 25,
    perfectBonusCoins: 5,
    mainWord: "SUN",
    miniWords: ["SAP", "URN", "NET"]
  }),
  createMockLevel({
    id: "4",
    bookId: "nce-1",
    unitId: "nce-1-u2",
    title: "Book Corner",
    difficulty: "easy",
    rewardCoins: 25,
    hintCost: 25,
    perfectBonusCoins: 5,
    mainWord: "BOOK",
    miniWords: ["BELL", "OVEN", "OKAY", "KING"]
  }),
  createMockLevel({
    id: "5",
    bookId: "nce-1",
    unitId: "nce-1-u2",
    title: "Hand Practice",
    difficulty: "easy",
    rewardCoins: 25,
    hintCost: 25,
    perfectBonusCoins: 5,
    mainWord: "HAND",
    miniWords: ["HAT", "ANT", "NEST", "DOG"]
  }),
  createMockLevel({
    id: "6",
    bookId: "nce-1",
    unitId: "nce-1-u2",
    title: "Fish Set",
    difficulty: "easy",
    rewardCoins: 30,
    hintCost: 25,
    perfectBonusCoins: 8,
    mainWord: "FISH",
    miniWords: ["FAN", "INK", "SUN", "HEN"]
  }),
  createMockLevel({
    id: "7",
    bookId: "nce-2",
    unitId: "nce-2-u1",
    title: "Train Trip",
    difficulty: "easy",
    rewardCoins: 30,
    hintCost: 25,
    perfectBonusCoins: 8,
    mainWord: "TRAIN",
    miniWords: ["TAP", "RUG", "ANT", "INK", "NET"]
  }),
  createMockLevel({
    id: "8",
    bookId: "nce-2",
    unitId: "nce-2-u1",
    title: "Beach Walk",
    difficulty: "easy",
    rewardCoins: 30,
    hintCost: 25,
    perfectBonusCoins: 8,
    mainWord: "BEACH",
    miniWords: ["BUS", "EGG", "AIR", "CUP", "HAT"]
  }),
  createMockLevel({
    id: "9",
    bookId: "nce-2",
    unitId: "nce-2-u1",
    title: "River Route",
    difficulty: "medium",
    rewardCoins: 35,
    hintCost: 25,
    perfectBonusCoins: 8,
    mainWord: "RIVER",
    miniWords: ["RAT", "INN", "VAN", "EAR", "RED"]
  }),
  createMockLevel({
    id: "10",
    bookId: "nce-2",
    unitId: "nce-2-u2",
    title: "Apple Plate",
    difficulty: "easy",
    rewardCoins: 35,
    hintCost: 25,
    perfectBonusCoins: 8,
    mainWord: "APPLE",
    miniWords: ["ANT", "PEN", "PAN", "LOG", "EAR"]
  }),
  createMockLevel({
    id: "11",
    bookId: "nce-2",
    unitId: "nce-2-u2",
    title: "Bread Basket",
    difficulty: "medium",
    rewardCoins: 35,
    hintCost: 25,
    perfectBonusCoins: 8,
    mainWord: "BREAD",
    miniWords: ["BAT", "RUG", "EAR", "ANT", "DOG"]
  }),
  createMockLevel({
    id: "12",
    bookId: "nce-2",
    unitId: "nce-2-u2",
    title: "Salad Bowl",
    difficulty: "medium",
    rewardCoins: 40,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "SALAD",
    miniWords: ["SUN", "ANT", "LOG", "ARM", "DOG"]
  }),
  createMockLevel({
    id: "13",
    bookId: "nce-3",
    unitId: "nce-3-u1",
    title: "School Notes",
    difficulty: "medium",
    rewardCoins: 40,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "SCHOOL",
    miniWords: ["SUN", "CAT", "HAT", "OIL", "OAK", "LOG"]
  }),
  createMockLevel({
    id: "14",
    bookId: "nce-3",
    unitId: "nce-3-u1",
    title: "Lesson Time",
    difficulty: "medium",
    rewardCoins: 40,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "LESSON",
    miniWords: ["LOG", "EAR", "SUN", "SAP", "OIL", "NET"]
  }),
  createMockLevel({
    id: "15",
    bookId: "nce-3",
    unitId: "nce-3-u1",
    title: "Pencil Box",
    difficulty: "medium",
    rewardCoins: 45,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "PENCIL",
    miniWords: ["PAN", "EAR", "NET", "CUP", "INK", "LOG"]
  }),
  createMockLevel({
    id: "16",
    bookId: "nce-3",
    unitId: "nce-3-u2",
    title: "Flower Field",
    difficulty: "medium",
    rewardCoins: 45,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "FLOWER",
    miniWords: ["FAN", "LOG", "OIL", "WEB", "EAR", "RAT"]
  }),
  createMockLevel({
    id: "17",
    bookId: "nce-3",
    unitId: "nce-3-u2",
    title: "Forest Path",
    difficulty: "medium",
    rewardCoins: 45,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "FOREST",
    miniWords: ["FAN", "OAK", "RUG", "EAR", "SUN", "TOP"]
  }),
  createMockLevel({
    id: "18",
    bookId: "nce-3",
    unitId: "nce-3-u2",
    title: "Garden Gate",
    difficulty: "medium",
    rewardCoins: 50,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "GARDEN",
    miniWords: ["GEM", "ANT", "RAT", "DOG", "EAR", "NET"]
  }),
  createMockLevel({
    id: "19",
    bookId: "nce-4",
    unitId: "nce-4-u1",
    title: "Future Plans",
    difficulty: "medium",
    rewardCoins: 50,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "FUTURE",
    miniWords: ["FAN", "URN", "TOP", "USE", "RAT", "EAR"]
  }),
  createMockLevel({
    id: "20",
    bookId: "nce-4",
    unitId: "nce-4-u1",
    title: "Memory Links",
    difficulty: "medium",
    rewardCoins: 50,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "MEMORY",
    miniWords: ["MAP", "EAR", "MAN", "OIL", "RED", "YET"]
  }),
  createMockLevel({
    id: "21",
    bookId: "nce-4",
    unitId: "nce-4-u1",
    title: "Dream Notes",
    difficulty: "medium",
    rewardCoins: 55,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "DREAM",
    miniWords: ["DOG", "RUG", "EAR", "ANT", "MAP"]
  }),
  createMockLevel({
    id: "22",
    bookId: "nce-4",
    unitId: "nce-4-u2",
    title: "Heroes Page",
    difficulty: "medium",
    rewardCoins: 55,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "HEROES",
    miniWords: ["HAT", "EAR", "RAT", "OIL", "EGG", "SUN"]
  }),
  createMockLevel({
    id: "23",
    bookId: "nce-4",
    unitId: "nce-4-u2",
    title: "Voyage Words",
    difficulty: "medium",
    rewardCoins: 55,
    hintCost: 25,
    perfectBonusCoins: 10,
    mainWord: "VOYAGE",
    miniWords: ["VAN", "OIL", "YET", "ANT", "GEM", "EAR"]
  }),
  createMockLevel({
    id: "24",
    bookId: "nce-4",
    unitId: "nce-4-u2",
    title: "Legend Lines",
    difficulty: "medium",
    rewardCoins: 60,
    hintCost: 25,
    perfectBonusCoins: 12,
    mainWord: "LEGEND",
    miniWords: ["LOG", "EAR", "GEM", "EGG", "NET", "DOG"]
  })
] satisfies Level[];
